language: node_js
services:
  - mysql
node_js: "8"
branches:
  only:
  - master
cache:
  directories:
    - node_modules
dist: precise
before_install:
  # - mysql -e 'CREATE DATABASE IF NOT EXISTS testdb;'
  - mysql -u root -e "CREATE DATABASE testdb;"
  - mysql -u root -e "GRANT ALL PRIVILEGES ON testdb.* TO 'travis'@'%';";
