language: node_js
services:
  - mysql
node_js: "8"
branches:
  only:
  - master
cache:
  directories:
    - node_modules
dist: precise
before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS testdb;'
